### ISSUE TITLE
Error:(37, 9) Attribute instrumentation#android.test.InstrumentationTestRunner@label value=(Tests for CardView sample) from AndroidManifest.xml:37:9

### ISSUE THREAD

**Issue by sphairo** [googlesamples/android-CardView#2]
Error:(37, 9) Execution failed for task ':Application:processDebugTestManifest'.

> java.lang.RuntimeException: Manifest merger failed : Attribute instrumentation#android.test.InstrumentationTestRunner@label value=(Tests for CardView sample) from AndroidManifest.xml:37:9
>     is also present at manifestMerger3603637974806095367.xml:15:22 value=(Tests for com.example.android.cardview)
>     Suggestion: add 'tools:replace="android:label"' to <instrumentation> element at AndroidManifest.xml:35:5 to override

**Comment by thagikura** [comment]
Thanks for your report.

We'll address the issue anytime soon.

**Comment by thagikura** [comment]
Fixed by 7680b4b05b9c5d39f7489c548b3109a20091a142
